# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10T52gHvQ8vY59DB4cAYVJchfaTVe5XmP
"""

from src.data.load_data import load_data
from src.features.build_features import create_features
from src.models.train_model import train_model

def main():

    df = load_data("data/raw/train.csv")

    df = create_features(df)

    X = df.drop("target", axis=1)
    y = df["target"]

    model = train_model(X, y)

if __name__ == "__main__":
    main()